import Ecto.Query
alias Data.Resumes
alias Data.Resumes.Education
alias Data.Resumes.Experience
alias Data.Resumes.PersonalInfo
alias Data.Resumes.Rated
alias Data.Resumes.Skill
alias Data.Resumes.Resume
alias Data.Accounts
alias Data.Accounts.User
alias Data.Accounts.Credential
alias Data.Repo
alias Data.Uploaders.ResumePhoto
alias Data.SpokenLanguageFactory
alias Data.ResumeFactory
alias Data.FactoryUser
alias Data.Factory
alias Data.RegistrationFactory
alias Data.UserFactory
alias Data.TextOnlyFactory
alias Data.Resumes.TextOnly
